### ISSUE TITLE
Example is broken

### ISSUE THREAD

**Issue by rgaiacs** [alandefreitas/citation_graph#5]
```
$ git rev-parse HEAD
e8494a33cf22c3ced75976359128b4c911fd7e6f
$ python citation_graph.py 
[{'citations': 'lu2008,angeline1994evolutionary,balakrishnan1995evolutionary,baldominos2018evolutionary', 'publisher': 'Springer', 'year': '2019', 'pages': '1--27', 'journal': 'Neural Computing and Applications', 'author': 'Baldominos, Alejandro and Saez, Yago and Isasi, Pedro', 'title': 'On the automated, evolutionary design of neural networks: past, present, and future', 'ENTRYTYPE': 'article', 'ID': 'baldominos2019automated'}, {'publisher': 'Elsevier', 'year': '2018', 'pages': '38--52', 'volume': '283', 'journal': 'Neurocomputing', 'author': 'Baldominos, Alejandro and Saez, Yago and Isasi, Pedro', 'title': 'Evolutionary convolutional neural networks: An application to handwriting recognition', 'ENTRYTYPE': 'article', 'ID': 'baldominos2018evolutionary'}, {'year': '1995', 'author': 'Balakrishnan, Karthik and Honavar, Vasant', 'title': 'Evolutionary design of neural architectures--a preliminary taxonomy and guide to literature', 'ENTRYTYPE': 'article', 'ID': 'balakrishnan1995evolutionary'}, {'publisher': 'IEEE', 'year': '1994', 'pages': '54--65', 'number': '1', 'volume': '5', 'journal': 'IEEE transactions on Neural Networks', 'author': 'Angeline, Peter J and Saunders, Gregory M and Pollack, Jordan B', 'title': 'An evolutionary algorithm that constructs recurrent neural networks', 'ENTRYTYPE': 'article', 'ID': 'angeline1994evolutionary'}, {'citations': 'lu2008', 'year': '2019', 'journal': 'arXiv preprint arXiv:1902.06827', 'author': 'Liang, Jason and Meyerson, Elliot and Hodjat, Babak and Fink, Dan and Mutch, Karl and Miikkulainen, Risto', 'title': 'Evolutionary neural automl for deep learning', 'ENTRYTYPE': 'article', 'ID': 'liang2019evolutionary'}, {'citations': 'deb2000fast,dong2018ppp,elsken2018efficient,hsu2018monas', 'bibsource': 'dblp computer science bibliography, https://dblp.org', 'biburl': 'https://dblp.org/rec/bib/journals/corr/abs-1810-03522', 'timestamp': 'Tue, 30 Oct 2018 10:49:09 +0100', 'eprint': '1810.03522', 'archiveprefix': 'arXiv', 'url': 'http://arxiv.org/abs/1810.03522', 'year': '2018', 'volume': 'abs/1810.03522', 'journal': 'CoRR', 'title': '{NSGA-NET:} {A} Multi-Objective Genetic Algorithm for Neural Architecture\nSearch', 'author': 'Zhichao Lu and\nIan Whalen and\nVishnu Boddeti and\nYashesh D. Dhebar and\nKalyanmoy Deb and\nErik D. Goodman and\nWolfgang Banzhaf', 'ENTRYTYPE': 'article', 'ID': 'lu2008'}, {'organization': 'Springer', 'year': '2000', 'pages': '849--858', 'booktitle': 'International conference on parallel problem solving from nature', 'author': 'Deb, Kalyanmoy and Agrawal, Samir and Pratap, Amrit and Meyarivan, Tanaka', 'title': 'A fast elitist non-dominated sorting genetic algorithm for multi-objective optimization: NSGA-II', 'ENTRYTYPE': 'inproceedings', 'ID': 'deb2000fast'}, {'citations': 'elsken2018efficient', 'year': '2019', 'pages': '1--21', 'number': '55', 'volume': '20', 'journal': 'Journal of Machine Learning Research', 'author': 'Elsken, Thomas and Metzen, Jan Hendrik and Hutter, Frank', 'title': 'Neural Architecture Search: A Survey.', 'ENTRYTYPE': 'article', 'ID': 'elsken2019neural'}, {'citations': 'kim2017nemo,miikkulainen2019evolving,real2017large,stanley2002evolving', 'year': '2018', 'journal': 'arXiv preprint arXiv:1804.09081', 'author': 'Elsken, Thomas and Metzen, Jan Hendrik and Hutter, Frank', 'title': 'Efficient multi-objective neural architecture search via lamarckian evolution', 'ENTRYTYPE': 'article', 'ID': 'elsken2018efficient'}, {'publisher': 'MIT Press', 'year': '2002', 'pages': '99--127', 'number': '2', 'volume': '10', 'journal': 'Evolutionary computation', 'author': 'Stanley, Kenneth O and Miikkulainen, Risto', 'title': 'Evolving neural networks through augmenting topologies', 'ENTRYTYPE': 'article', 'ID': 'stanley2002evolving'}, {'organization': 'JMLR. org', 'year': '2017', 'pages': '2902--2911', 'booktitle': 'Proceedings of the 34th International Conference on Machine Learning-Volume 70', 'author': 'Real, Esteban and Moore, Sherry and Selle, Andrew and Saxena, Saurabh and Suematsu, Yutaka Leon and Tan, Jie and Le, Quoc V and Kurakin, Alexey', 'title': 'Large-scale evolution of image classifiers', 'ENTRYTYPE': 'inproceedings', 'ID': 'real2017large'}, {'publisher': 'Elsevier', 'year': '2019', 'pages': '293--312', 'booktitle': 'Artificial Intelligence in the Age of Neural Networks and Brain Computing', 'author': 'Miikkulainen, Risto and Liang, Jason and Meyerson, Elliot and Rawal, Aditya and Fink, Daniel and Francon, Olivier and Raju, Bala and Shahrzad, Hormoz and Navruzyan, Arshak and Duffy, Nigel and others', 'title': 'Evolving deep neural networks', 'ENTRYTYPE': 'incollection', 'ID': 'miikkulainen2019evolving'}, {'year': '2017', 'booktitle': 'ICML 2017 AutoML Workshop', 'author': 'Kim, Ye-Hoon and Reddy, Bhargava and Yun, Sojung and Seo, Chanwon', 'title': 'Nemo: Neuro-evolution with multiobjective optimization of deep neural network for speed and accuracy', 'ENTRYTYPE': 'inproceedings', 'ID': 'kim2017nemo'}, {'year': '2018', 'author': 'Dong, Jin-Dong and Cheng, An-Chieh and Juan, Da-Cheng and Wei, Wei and Sun, Min', 'title': 'PPP-Net: Platform-aware progressive search for pareto-optimal neural architectures', 'ENTRYTYPE': 'article', 'ID': 'dong2018ppp'}, {'year': '2018', 'journal': 'arXiv preprint arXiv:1806.10332', 'author': 'Hsu, Chi-Hung and Chang, Shu-Huan and Liang, Jhao-Hong and Chou, Hsin-Ping and Liu, Chun-Hao and Chang, Shih-Chieh and Pan, Jia-Yu and Chen, Yu-Ting and Wei, Wei and Juan, Da-Cheng', 'title': 'Monas: Multi-objective neural architecture search using reinforcement learning', 'ENTRYTYPE': 'article', 'ID': 'hsu2018monas'}]
[]
[]
OrderedDict()
Traceback (most recent call last):
  File "citation_graph.py", line 179, in <module>
    main()
  File "citation_graph.py", line 56, in main
    positionx = (dict_qpycurr[entry['year']])/dict_qpy[entry['year']]
KeyError: '1995'
```

**Comment by alandefreitas** [comment]
Solved...
